"""added nutrition and other models

Revision ID: 28d7d8110609
Revises: 0f1e7d5b3a2c
Create Date: 2026-09-02 22:47:04.603703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28d7d8110609'
down_revision = '0f1e7d5b3a2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('studios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('external_place_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('claimed_by_user_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('uq_studios_external_place_id', ['external_place_id'])

        batch_op.create_foreign_key('fk_studios_claimed_by_user_id', 'users', ['claimed_by_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('studios', schema=None) as batch_op:
        batch_op.drop_constraint('uq_studios_external_place_id', type_='foreignkey')
        batch_op.drop_constraint('uq_studios_external_place_id', type_='unique')
        batch_op.drop_column('claimed_by_user_id')
        batch_op.drop_column('external_place_id')
        batch_op.drop_column('source')

    # ### end Alembic commands ###
