"""Add discovered_gym_cache

Revision ID: b2571481c38c
Revises: 67b36c6f0731
Create Date: 2026-09-03 09:29:33.937075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2571481c38c'
down_revision = '67b36c6f0731'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discovered_gym_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cell_key', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('discovered_gym_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discovered_gym_cache_cell_key'), ['cell_key'], unique=True)

    op.create_table('food_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('calories_per_100g', sa.Float(), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=False),
    sa.Column('carbs_g', sa.Float(), nullable=False),
    sa.Column('fat_g', sa.Float(), nullable=False),
    sa.Column('external_source_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_source_id')
    )
    with op.batch_alter_table('food_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_food_items_name'), ['name'], unique=False)

    op.create_table('pass_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('food_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('food_item_id', sa.Integer(), nullable=False),
    sa.Column('quantity_g', sa.Float(), nullable=False),
    sa.Column('meal_type', sa.String(), nullable=False),
    sa.Column('logged_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['food_item_id'], ['food_items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('food_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_food_logs_logged_at'), ['logged_at'], unique=False)

    op.create_table('idempotency_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=64), nullable=False),
    sa.Column('response_body', sa.JSON(), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', 'user_id', 'scope', name='uq_idempotency_key_user_scope')
    )
    with op.batch_alter_table('idempotency_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_idempotency_keys_key'), ['key'], unique=False)

    op.create_table('nutrition_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('goal', sa.String(), nullable=False),
    sa.Column('daily_calorie_target', sa.Integer(), nullable=True),
    sa.Column('protein_target_g', sa.Integer(), nullable=True),
    sa.Column('carbs_target_g', sa.Integer(), nullable=True),
    sa.Column('fat_target_g', sa.Integer(), nullable=True),
    sa.Column('dietary_restrictions', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('waitlist_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('notified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['fitness_classes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'class_id', name='uq_waitlist_user_class')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('waitlist_entries')
    op.drop_table('nutrition_profiles')
    with op.batch_alter_table('idempotency_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idempotency_keys_key'))

    op.drop_table('idempotency_keys')
    with op.batch_alter_table('food_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_food_logs_logged_at'))

    op.drop_table('food_logs')
    op.drop_table('pass_plans')
    with op.batch_alter_table('food_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_food_items_name'))

    op.drop_table('food_items')
    with op.batch_alter_table('discovered_gym_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discovered_gym_cache_cell_key'))

    op.drop_table('discovered_gym_cache')
    # ### end Alembic commands ###
